"""empty message

Revision ID: 0be1a3caa50c
Revises: 89ae22049236
Create Date: 2021-01-06 19:47:50.198331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be1a3caa50c'
down_revision = '89ae22049236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_game_name'), 'ratings', ['game_name'], unique=False)
    op.add_column('games', sa.Column('authors', sa.String(length=64), nullable=False))
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('games', 'authors')
    op.drop_index(op.f('ix_ratings_game_name'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
