"""empty message

Revision ID: 14a87fd3668c
Revises: 0be1a3caa50c
Create Date: 2021-01-07 01:32:04.483176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a87fd3668c'
down_revision = '0be1a3caa50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('preview_img', sa.String(length=27), nullable=False))
    op.create_unique_constraint(None, 'games', ['preview_img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'preview_img')
    # ### end Alembic commands ###
