"""empty message

Revision ID: 28a5bc2879dd
Revises: dd84e32dd080
Create Date: 2021-02-03 17:34:23.175504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a5bc2879dd'
down_revision = 'dd84e32dd080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_plays', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('games', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('players', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('ratings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    op.alter_column('players', 'created_at', server_default=sa.text('now()'))
    op.alter_column('games', 'created_at', server_default=sa.text('now()'))
    op.alter_column('ratings', 'created_at', server_default=sa.text('now()'))
    op.alter_column('game_plays', 'created_at', server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'updated_at')
    op.drop_column('players', 'updated_at')
    op.drop_column('games', 'updated_at')
    op.drop_column('game_plays', 'updated_at')
    # ### end Alembic commands ###
