"""empty message

Revision ID: 524278b753f3
Revises: 
Create Date: 2021-01-06 13:54:42.770591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524278b753f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('player_email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['player_email'], ['players.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_plays',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('player_email', sa.String(length=50), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_email'], ['players.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_plays')
    op.drop_table('games')
    op.drop_table('players')
    # ### end Alembic commands ###
