"""empty message

Revision ID: 72dad04d15af
Revises: c3520087ed73
Create Date: 2021-01-12 23:07:05.076191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dad04d15af'
down_revision = 'c3520087ed73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ratings_game_name', table_name='ratings')
    op.drop_column('ratings', 'game_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('game_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_index('ix_ratings_game_name', 'ratings', ['game_name'], unique=False)
    # ### end Alembic commands ###
