"""empty message

Revision ID: 768e2667a809
Revises: cce92419f7aa
Create Date: 2021-01-16 19:33:50.968120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768e2667a809'
down_revision = 'cce92419f7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('description', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'description')
    # ### end Alembic commands ###
