"""empty message

Revision ID: c3520087ed73
Revises: 14a87fd3668c
Create Date: 2021-01-12 22:50:21.017013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3520087ed73'
down_revision = '14a87fd3668c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('player_email', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'ratings', 'players', ['player_email'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'player_email')
    # ### end Alembic commands ###
