"""empty message

Revision ID: cce92419f7aa
Revises: 07d625c1ae4c
Create Date: 2021-01-16 01:18:39.975214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce92419f7aa'
down_revision = '07d625c1ae4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_messages', sa.Column('game_play_id', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_messages', 'game_play_id')
    # ### end Alembic commands ###
