"""empty message

Revision ID: d98e5383b2b0
Revises: 768e2667a809
Create Date: 2021-01-17 21:50:30.997027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98e5383b2b0'
down_revision = '768e2667a809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_messages', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_messages', 'updated_at')
    # ### end Alembic commands ###
